import Head from 'next/head'
import React from 'react'
import ItemSlider from '../../components/ItemSlider'
import ProductNavbar from '../../components/ProductNavbar'
import itemData from '../../data/ItemData'

const Vivid_Percussion_01 = () => {
  return (
    <>
      <Head>
        <title>MYNTIAN STORE</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/dog.png" />
      </Head>
      <ItemSlider/>
      <ProductNavbar position="absolute" link="https://www.mediafire.com/file/qumxnemi69wbdnq/Myntian_Vivid_Percussion_1.zip/file" row={1} col={0} background="Vivid_Percussion_01"/>
    </>
  )
}

export default Vivid_Percussion_01