import Head from 'next/head'
import React from 'react'
import Storerow from '../components/Storerow'

const store = () => {
  return (
    <>
      <Head>
        <title>MYNTIAN STORE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/dog.png" />
      </Head>

      <Storerow />
    </>
  )
}

export default store